# Generated by Django 3.2 on 2021-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
