# Generated by Django 3.2 on 2021-04-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_options'),
        ('albums', '0002_auto_20210420_1000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'name')},
        ),
    ]
