# Generated by Django 3.2 on 2021-04-20 14:56

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=albums.models.upload_to, validators=[albums.models.extension_validator])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
